name: hnn_core_dev
channels:
- conda-forge
dependencies:
- python>=3.8,<3.9
- pip
- numpy
- scipy
- matplotlib
- numba
- joblib
- openmpi
- mpi4py
- pandas
- xlrd
- scikit-learn
- h5py
- pillow
- statsmodels
- jupyter
- joblib
- psutil
- pytest
- flake8
- numexpr
- traits
- pyface
- traitsui
- imageio
- tqdm
- spyder-kernels>=1.10.0
- imageio-ffmpeg>=0.4.1
- vtk>=9.0.1
- pyvista>=0.24
- pyvistaqt>=0.2.0
- mayavi
- PySurfer
- dipy
- nibabel
- nilearn
- python-picard
- pyqt
- mne
- mffpy>=0.5.7
- pip:
  - NEURON
  - numpydoc
  - sphinx-gallery
  - sphinx_bootstrap_theme
  - pillow
  - psutil
