name: hnn_dev
channels:
- default
dependencies:
- python>=3.7,<3.9
- pip
- numpy
- scipy
- matplotlib
- joblib
- openmpi
- mpi4py
- pip:
  - NEURON
  - mne
  - numpydoc
  - sphinx-gallery
  - sphinx_bootstrap_theme
  - pillow
  - psutil
